package com.mra.rentcarcompose.navigation


const val CAR_DATA_ARGUMENT_KEY = "CAR_DATA_ARGUMENT_KEY"



const val LOGIN_SCREEN_ROUTE = "LOGIN_SCREEN_ROUTE"
const val CARS_LIST_SCREEN_ROUTE = "CARS_LIST_SCREEN_ROUTE"
const val BOOKING_CAR_SCREEN_ROUTE = "BOOKING_CAR_SCREEN_ROUTE/{$CAR_DATA_ARGUMENT_KEY}"
